name: Build and Publish NPM Package

on:
  push:
    branches: [ custom-htmlmesh ]
    tags:
      - 'v*'
    paths:
      - 'HtmlMesh/**'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 'HtmlMesh'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'
          scope: '@rooom'

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Extract package version from tag
        id: tag_version
        run: echo "::set-output name=version::${GITHUB_REF#refs/tags/v}"

      - name: Extract package version from package.json
        id: package_json_version
        run: echo "::set-output name=version::$(node -p "require('./package.json').version")"

      - name: Check versions
        run: |
          if [ "${{ steps.tag_version.outputs.version }}" == "${{ steps.package_json_version.outputs.version }}" ]; then
            echo "Tag version (${{ steps.tag_version.outputs.version }}) does not match package.json version (${{ steps.package_json_version.outputs.version }}). Aborting!"
            exit 1
          fi

      - name: Update package version
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          npm version $TAG_VERSION --no-git-tag-version

      - name: Publish package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}