name: Build and Publish NPM Package

on:
  push:
    branches: [ custom-htmlmesh ]
    tags:
      - 'v*'
    paths:
      - 'HtmlMesh/**'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 'HtmlMesh'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'
          scope: '@rooom'

      - name: Configure npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          echo "@rooom:registry=https://registry.npmjs.org/" >> .npmrc

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Check versions
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          if [ "$TAG_VERSION" != "$PACKAGE_VERSION" ]; then
            echo "Tag version ($TAG_VERSION) does not match package.json version ($PACKAGE_VERSION). Aborting!"
            exit 1
          fi

      - name: Publish package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}