name: Sync Upstream Changes

on:
  schedule:
    - cron: '0 0 * * 1'  # Weekly on Monday
  workflow_dispatch:      # Manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Check and sync upstream changes
        id: sync
        run: |
          # Setup git
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          # Generate desired branch name with timestamp
          BRANCH="sync/upstream-$(date +%Y%m%d-%H%M%S)"

          # Run sync script
          npm run sync-upstream
          
          # Check if there are changes
          if [[ -n "$(git status --porcelain)" ]]; then
            git add .
            git commit -m "chore: sync upstream HtmlMesh changes"
            echo "changes_detected=true" >> $GITHUB_OUTPUT
            echo "branch=$BRANCH" >> $GITHUB_OUTPUT
          else
            echo "No changes detected"
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.sync.outputs.changes_detected == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.sync.outputs.branch }}
          base: master
          title: '⬆️ Sync upstream HtmlMesh changes'
          body: |
            🤖 This PR was automatically created to sync the latest HtmlMesh implementation from BabylonJS.
            
            ### ⚠️ Review Needed
            Please review the changes carefully, especially if you have local modifications that need to be preserved.
            
            ### 📝 Next Steps
            1. Review the changes
            3. Apply any needed custom modifications
            4. Merge when ready
          labels: |
            sync
            dependencies
          draft: false